# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Dywb/uVqYf8yTYNX2D5a/4y4jK6+r95GbnzdEj08wgCuoCiXKutiNwI+v3V3zCRSe8j4MnPMjfP7CAwqfcd4E321OeawiyEtbt+KIPQuVxNvpbnDuYvfaIb0g/xuYkOmU3hOAJ9y4qDFVk1LHOfqZQ2W0hxRIH5yAPhTBxwHZJ9Q231xk1vPnayf+iawDntiNbt/1k42xxkzGDYRD5TTz4un0u1aPEl2j44s6ZdPdBlXTVxNP1o/beHoQFxqjqNL9gGvYIJcILzgu4vafmknxXAPwrdPoK8TurqsySEG0c027rNfxHN0nhjbB3lKxjyLdbn/t1wCXq3oR/DY8DdiENMygVlKj5SVZCRgeJ/2pBUICjr6YVoEI/iJrAZatiSceLx65K/OAzC7jS6cFKQQDQn/OaHmaiRh6C7oxmnhoX7SRbiilSOgkAkuyqXbr96kV2Yk2UirJh4oQI1FAvkN28yYko2IVVnZKkJ0DF4FHs4SL5NCAwY8T4A61XJWVNxSQ0Y0aAAZWYiGt1CZY48SGensny8nXlmrojGPCPhv3vtugrlLmgDtnKWpIlwutqIHB047Jhe4v4gR1ZJu+2w1Kf1INKPjuYlEvP1HfGXLQXY48i0jWk5ObeQ4Fsdz9WHRTnRnY9bjf+uT52Zcjp804Jhc9sdpOVKIQmVSNJz4/E8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
