travis:
  secure:
    BINSTAR_TOKEN: UOKj9SRk4KeszCabWlF1AVEFciT5bLHin6KaOq7IbC2EQyjvT3ofYGE9pAOBtsQZuOVcZsiAFts55xWXI/nGns7/42QhUCXBsG26Ur8BCAfkDjrZ5EyN7ZL1vFLbC5UknIVG+bwF+NbJWuL/mj5g0RyOfrQsg4mCYLOKFNmR2epyjgbr6BPU1MaNtD3TaXXiNuFu+dagNSh5IlgS+lk/JDCVboqJVWDgNbD7sEKybTLFiPHNBJH3uX733sc2Mv7JZ5nl8oQAoefVRCqFoqWhammblYb9llvzODR/DAOYNHF3TLnXaww41JRoBEE6I6mo+acP/99S9JpCSTkfa6CVZs8+QgDLnkKlZB1+OBQXM/9MgG0Xh9t1x1QA5Ovx19R/rDBUn9jt2DINqJKqs5MaOh4nz4SDtzoWT3QjmHbCtwZ40qQzu1LZM9kLSTTMbC5kkZkq6iOYY2H8mdlhhkqbHHc4M3yOrqmr1mJs1m4ImjwI4/Z5ykdx+T6WHATJjSrRAotxc3FLuKduKP71k/KIJcIHiXkGrrTt944oWATeerbFa5WRDWQGe/6aRTO9axS9r9Y/1IawP23JHWzrE4txxhb/807dUnYAhZhDhkqo/tIH/xtEoip441gWd2992iyORs0+JdD/lEh1ejboj9v9w+rsHcFxsSnRSbrJ2t6R6L4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
